image: node:latest

cache:
  paths:
  - node_modules/

stages:
  - install
  - __tests__

install:
  stage: install
  script:
    - npm install

lint:
  stage: __tests__
  script:
    - npm run lint

test:
  stage: __tests__
  script:
    - npm __tests__
