image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - install
  - test

install:
  stage: install
  script:
    - npm install

lint:
  stage: test
  script:
    - npm run lint

test:
  stage: test
  script:
    - npm test
